### ISSUE TITLE
NVDashboard build not working

### ISSUE THREAD

**Issue by nmcross** [NVIDIA/clara-train-examples#14]
However, I was interested in the NVDashboard functionality so I commented the

```
image: nvcr.io/nvidia/clara-train-sdk:v4.0
```
in the docker compose and then uncommented

```
build:
   context: ./dockerWGPUDashboardPlugin/    # Project root
   dockerfile: ./Dockerfile                 # Relative to context
image: clara-train-nvdashboard:v4.0
```
However when I run the startClaraTrainNoteBooks.sh I get a build error from docker saying…
```
An error occurred.
ValueError: The extension "jupyterlab-nvdashboard" does not yet support the current version of JupyterLab.
Conflicting Dependencies:
JupyterLab              Extension        Package
>=3.1.8 <3.2.0          >=2.0.0 <3.0.0   @jupyterlab/application
>=3.1.8 <3.2.0          >=2.0.0 <3.0.0   @jupyterlab/apputils
>=5.1.8 <5.2.0          >=4.0.0 <5.0.0   @jupyterlab/coreutils
>=17.0.1 <18.0.0        >=16.4.2 <17.0.0 react
>=17.0.1 <18.0.0        >=16.9.0 <17.0.0 react-dom
The command '/bin/sh -c jupyter labextension install jupyterlab-nvdashboard' returned a non-zero code: 1
ERROR: Service 'claratrain' failed to build : Build failed
```
How can I fix this or is nvdashboard ancient tech?
